'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
'''

def create_fibonacci(last_number):
	#fibo_list = [0, 1]
	for i in range(2,last_number):
		fibo_list.append(fibo_list[i-1]+fibo_list[i-2])
	return fibo_list

last_number=int(input('Enter the number of terms in your fibonacci list: '))

fibo_list = [0, 1]
print create_fibonacci(last_number)
for i in range (1, last_number):
	if fibo_list[i] % 2 == 0 and fibo_list[i] < 4000000:
		print fibo_list[i]
